### ISSUE TITLE
Ability to skip URL's

### ISSUE THREAD

**Issue by ghoneycutt** [tskirvin/puppet-lint-racism_terminology-check#1]
Would like to use this plugin, though 'master' is embedded in URL's. Specifically comments referencing code that use a branch named 'master'.

**Comment by tskirvin** [comment]
Hmm.  Well, for starters, let's rename that branch to 'main', good call.

Otherwise - what do you think, do we just need to skip 'http' and 'https'?  Can we ignore ftp, ssh, etc?  I'm trying to think of use cases where this matters.  (Alternately, is there a good library for this that we could import for a pre-chosen url matcher?)

**Comment by ghoneycutt** [comment]
I'm working on a fix now

**Comment by ghoneycutt** [comment]
I see you responding in real time.. if you have a sec could you join the puppet slack.

**Comment by tskirvin** [comment]
Merging in your change, I'm updating the version to match and currently remembering what to add to the dependencies.  Thanks!
